### ISSUE TITLE
Periodicity Extractor部分代码

### ISSUE THREAD

**Issue by lou-yimin** [Hank0626/PDF#10]
parser.add_argument('--period', type=int, nargs='+', default=[24, 12], help='period list')
获取period的方法是论文主要创新点之一（Periodicity Extractor），但是这部分的代码好像没有公布。
请问论文中公式2的代码可以公布吗，因为我没有明白Fu和Fk1的区别。

**Comment by Hank0626** [comment]
See #5.  Fu是k个最大幅值对应的频率；Fk1是在Fu中进一步选k1个最大幅值对应的频率，然后在被选完剩下的频率中选频率值最大的k2个频率
