### ISSUE TITLE
Period Patching

### ISSUE THREAD

**Issue by zhangtt2024** [Hank0626/PDF#2]
请问Period Patching中的p是怎么确定的？

**Comment by Hank0626** [comment]
您好，我们将`p`当做一个超参数进行输入，大致控制patch的数量在6～24个之间之间即可。

**Comment by Diroooomy** [comment]
那模型结构图中的Periodicity Extractor是怎么做的

**Comment by Hank0626** [comment]
> 那模型结构图中的Periodicity Extractor是怎么做的

通过对训练集进行傅立叶变换，然后选取幅值最大和高频率对应的周期长度。
这是一个先验操作，我们获得后直接当作超参输入模型
