### ISSUE TITLE
help，Please

### ISSUE THREAD

**Issue by gyy520cyaowu** [Hank0626/PDF#3]
May I ask what problems this model mainly solves in time series forecasting? This is what my teacher asked me. I am not sure. Please help.

**Comment by Hank0626** [comment]
Hi there, the basic idea of our work is decoupling time series into long-term and short-term variations. Transformers excel at globally modeling long-term dependencies, while CNNs are adept at precisely capturing short-term variations with local detail. We use Transformer to model long-term dependencies and CNN to model short-term variations. For more details, please refer to the origin paper: https://openreview.net/pdf?id=dp27P5HBBt.
