### ISSUE TITLE
predict_merge

### ISSUE THREAD

**Issue by Gongson** [Hank0626/PDF#4]
Hello，when I use PDF, an error come up here.

How to define the "predict_merge" in model（Autoformer, Informer and Transformer）?

We need to use "Parser" to add the argument — "predict_merge" firstly before using PDF,right?

**Comment by Hank0626** [comment]
Yes. If the model has the argument "predict_merge", then the arg parser should add it.

**Comment by Hank0626** [comment]
By the way, I recommend you run their official code if you want to obtain the results of other baselines (e.g. Autoformer, Informer, .etc).
