### ISSUE TITLE
frequency selection

### ISSUE THREAD

**Issue by Jimmyloua** [Hank0626/PDF#5]
Hello, I would like to ask where the "frequency selection" mentioned in the paper is in the code? I didn't find it in the official code implementation

**Comment by Hank0626** [comment]
We applied a Fourier transform to the entire training dataset to identify the frequency with the highest amplitude and the highest frequency. We then calculated the corresponding period, which was subsequently used as an input hyperparameter.

**Comment by Hank0626** [comment]
Since this was performed on the entire training set, we recorded the statistics directly and used them as hyperparameters.

**Comment by Jimmyloua** [comment]
thank you for your reply
