### ISSUE TITLE
特定数据集超参数的选取策略

### ISSUE THREAD

**Issue by TPF2017** [Hank0626/PDF#6]
您好，请问一下模型中几个主要参数 period、patch_len、stride 有大致的选取原则吗？比如傅里叶变换的高频是如何跟参数对应的，应该选择几个参数，参数之间有没有相关的关系。

**Comment by Hank0626** [comment]
`period `一般选取傅立叶变化以后幅值前几个对应的频率，对于周期性不强的数据，会适当增加的高频。`patch_len`是一段小于period长度即可，`stride`一般设置成和`patch_len`一致。
