### ISSUE TITLE
kernel_list的选取与周期的定义

### ISSUE THREAD

**Issue by jianlaigeng** [Hank0626/PDF#9]
您好，作者大大，在代码中没看到确定在周期的代码呢？还有一个问题kernel_list的大小是怎么确定的啊？可以麻烦您解答一下吗？谢谢

**Comment by Hank0626** [comment]
您好，周期问题见https://github.com/Hank0626/PDF/issues/5
kernel_list的大小一般小于最小period_len并且size逐渐减小即可，参见一般1D卷积的设置方式。

**Comment by jianlaigeng** [comment]
> 您好，周期问题见#5 kernel_list的大小一般小于最小period_len并且size逐渐减小即可，参见一般1D卷积的设置方式。
嗯嗯，好的谢谢回复
